### ISSUE TITLE
【フォーム】ファイルを添付するとエラーになる

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2938]
baserCMS version : 4.9.0-dev

ファイルを添付するとエラー画面になる

エラーログ

```
[Error] 2023-12-12 19:10:41 ---------------------------------------------------------
[SocketException] ファイルが見つかりません。: "/var/www/html/_baser/seto1/app/webroot/files/mail/limited/1/messages/Array"
Request URL: /_baser/seto1/contact/submit
Stack Trace:
#0 /var/www/html/_baser/seto1/lib/Baser/Controller/BcAppController.php(1132): CakeEmail->attachments(Array)
#1 /var/www/html/_baser/seto1/lib/Baser/Plugin/Mail/Controller/MailController.php(663): BcAppController->sendMail('admin@test.test', '\xE3\x80\x90baserCMS\xE3\x80\x91\xE3...', Array, Array)
#2 /var/www/html/_baser/seto1/lib/Baser/Plugin/Mail/Controller/MailController.php(410): MailController->_sendEmail(Array)
#3 [internal function]: MailController->submit()
#4 /var/www/html/_baser/seto1/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(MailController), Array)
#5 /var/www/html/_baser/seto1/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/html/_baser/seto1/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(MailController), Object(CakeRequest))
#7 /var/www/html/_baser/seto1/app/webroot/index.php(123): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by seto1** [comment]
5系とはまた違った現象

https://github.com/baserproject/basercms/issues/2816
https://github.com/baserproject/basercms/issues/2936

**Comment by seto1** [comment]
再度確認すると再現しなかったためクローズします。
フォルダの状態だとは思うのですが原因不明です。
